### ISSUE TITLE
Remove Backdrop from repo

### ISSUE THREAD

**Issue by ghost** [backdrop-ops/backdrop-tugboat#10]
Based on the discussion in https://github.com/backdrop-ops/backdrop-tugboat/pull/8 we want to try removing Backdrop from this repo so it's just the Tugboat directory and a README explaining things. Then we can setup Tugboat to download the latest Backdrop, which'll save having to merge it in manually each release.

**Comment by ghost** [comment]
PR seems to be working: https://github.com/backdrop-ops/backdrop-tugboat/pull/11

It takes longer to build the preview than when Backdrop was part of core, but since this only affects the base preview (and not the preview built when someone tries to demo Backdrop) then I think it's better this way.

Care to review @quicksketch or @klonos?

**Comment by quicksketch** [comment]
Wow cool!!

One thing I see is that this command will probably download the 1.x version of Backdrop, not an official release:
```
wget https://github.com/backdrop/backdrop/releases/latest/download/backdrop.zip -P $TUGBOAT_ROOT
```

I think for our front-facing demo, we should use the latest stable release. Which that may mean we need to update the repo still after every release. Or possibly query something (even backdropcms.org itself) to determine which version is the latest version.

**Comment by ghost** [comment]
@quicksketch That URL downloads the latest *release* of Backdrop. That's currently `1.15.1`.

I got that URL from this GitHub Help page: https://help.github.com/en/github/administering-a-repository/linking-to-releases

> You can share every release you create on GitHub with a unique URL.

> To link directly to a download of your latest release asset, link to `/owner/name/releases/latest/download/asset-name.zip`.

I just tested that link for Backdrop and looked in `/core/includes/bootstrap.inc`. It shows `define('BACKDROP_VERSION', '1.15.1');` (whereas the latest code in the repo has `define('BACKDROP_VERSION', '1.16.x-dev');` (https://github.com/backdrop/backdrop/blob/1.x/core/includes/bootstrap.inc)).

So this does indeed download the latest *release* from the Releases page: https://github.com/backdrop/backdrop/releases

**Comment by klonos** [comment]
Yup, what @BWPanda said ^^ that link gets the latest _release_ 👍

**Comment by quicksketch** [comment]
Another thought on this: Since we're effectively creating a completely different codebase, maybe we should just make a new repository rather than continuing this one? Perhaps a name like `backdrop-ops/tugboat-demos`?

**Comment by ghost** [comment]
@quicksketch What would happen to this one then? I don't mind creating a new repo, as long as this one gets deleted. Otherwise I foresee confusion in the future...

**Comment by ghost** [comment]
Setting up a new repo here: https://github.com/backdrop-ops/tugboat-demos

**Comment by ghost** [comment]
New repo seems to be working (from my testing), so I pointed B.org at it and now that seems to be working too.
