### ISSUE TITLE
Start Using Tags for Releases

### ISSUE THREAD

**Issue by quicksketch** [backdrop-ops/backdrop-tugboat#12]
Each new release of Backdrop core, I push a change into the `master` branch. That currently includes merging in core, but after https://github.com/backdrop-ops/backdrop-tugboat/issues/10, that would be mostly automatic.

However, after the release, it's updating the sandboxes in Tugboat's UI that becomes a problem. In order to have the sandboxes updated, the "base preview" must be rebuilt. This causes a few problems, roughly covered by this screenshot:

![image](https://user-images.githubusercontent.com/100206/83369221-7a324180-a370-11ea-86c8-c58fee36ca58.png)

The problem is that rebuilding is necessary to get the latest version of Backdrop, BUT in doing so, we have the following choices:

- Using the `Rebuild previews built from this one when finished` option, all demo sandboxes are destroyed and recreated. Temporarily, we also exceed our 40GB quota while they are being rebuilt, and no new demos can be created until it finishes.
- If we do not use the `Rebuild previews built from this one when finished` option, then all demos expand permanently from being ~200MB each to 1.4GB each. Which then exceeds the quota until the sandboxes are reduced in number (usually meaning deleting them).

In short, rebuilding a single preview image causes problems. Right now we only have one, the `master` preview. We should start creating a tag for every base preview instead, then switch the demos to use the new tag after each release in the backdropcms.org Tugboat UI:

![image](https://user-images.githubusercontent.com/100206/83369438-3ab82500-a371-11ea-8137-591203977388.png)

Keep in mind that new tags end up in the URL, e.g. `https://master-anjt21dscwye8qlm8qm4eebqcltlyyp1.tugboat.qa/` where `master` is the branch or tag name. So perhaps we should name the releases something like `1-16-3` (using dashes instead of dots) to be URL-friendly.

In using a tag for each release, we wouldn't need to rebuild existing previews. They'd stay on the version they were created on. New previews would use the new tag. And we wouldn't have problems of exceeding our quota every release.

After all old demos are destroyed (after 24 hours), we can delete the previous base preview. In reality, we'd probably do this once per release. When we make a new base preview, delete the one that is now 2 versions behind.

**Comment by quicksketch** [comment]
Could I get your thoughts on this @BWPanda?

**Comment by quicksketch** [comment]
Update: Turns out that a tag like `1.16.1` gets turned into `1-16-1` in the URL anyway. However, since right now we merge directly from the main Backdrop core repo, my local ends up having a conflict with the 1.16.1 tag used by core. If we completed #10, this might no longer be a problem.

**Comment by ghost** [comment]
Sounds like a plan, I'm just not sure how to execute it (been away from Tugboat too long I guess)...

**Comment by ghost** [comment]
Ok, finally got my head around this issue and I agree that works out better. The [new repo](https://github.com/backdrop-ops/tugboat-demos) uses tags, so each time a new version of Backdrop is released we'll need to update the Tugboat script in that repo to point to the new tag (when downloading Backdrop), then make a new tag of that repo to match. Then update B.org to point to the new Tugboat tag. Make sense?

**Comment by ghost** [comment]
Will close this issue now. Release checklist to be updated in https://github.com/backdrop/backdrop-issues/issues/4736
