### ISSUE TITLE
Either disable `trusted_host_patterns` on demo, or configure it properly

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdrop-tugboat#3]
Not ideal to have a warning in every demo site people spin.

PR to disable: #1 
PR to configure: #2

**Comment by quicksketch** [comment]
Yep agreed. I think configuring (option 2) is better. However, let's move that configuration to `.tugboat/settings.local.php` instead of directly in `settings.php`. Otherwise I'll get merge conflicts in the future when we pull in Backdrop core updates.

**Comment by quicksketch** [comment]
Fixed in https://github.com/backdrop-ops/backdrop-tugboat/commit/f0d10e3200c376e995e4c957eb3894f5edeae47d.
